---
- name: install pip3
  apt: name=python3-pip state=present

- name: Install python-docker
  pip:
    name: docker-compose

- name: Create a folder for docker-compose
  file:
    path: "{{cool_clock_install_directory}}"
    state: directory

- name: Generate docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{cool_clock_install_directory}}/docker-compose.yml"

- name: Start docker-compose
  docker_compose:
    project_src: "{{cool_clock_install_directory}}"
