version: '3.7'

networks:
  loki:

services:

  cool_clock:
    image: leosimonetti/devops-lab1-flask:latest
    volumes:
      - ./visits.txt:/visits.txt
    ports:
      - "80:5000"
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        max-file: 2
        max-size: 30m
    deploy:
      resources:
        limits:
          memory: 50M
  loki:
    image: grafana/loki:1.4.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    deploy:
      resources:
        limits:
          memory: 50M

  promtail:
    image: grafana/promtail:1.4.1
    volumes:
      - /var/lib/docker/containers/:/var/lib/docker/containers
      - ./docker-config.yml:/etc/promtail/docker-config.yml
    command: -config.file=/etc/promtail/docker-config.yml
    networks:
      - loki
    deploy:
      resources:
        limits:
          memory: 50M

  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    networks:
      - loki
    deploy:
      resources:
        limits:
          memory: 50M

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - loki
    deploy:
      resources:
        limits:
          memory: 50M
